spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yti
    username: yti
    password: yti
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080